// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Profile.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Profile TABLE
class TableProfile extends SqfEntityTableBase {
  TableProfile() {
    // declare properties of EntityTable
    tableName = 'profiles';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('name', DbType.text, isNotNull: true),
      SqfEntityFieldBase('picture', DbType.text),
      SqfEntityFieldBase('additions', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('correct_additions', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('subtractions', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('correct_subtractions', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('multiplications', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('correct_multiplications', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('divisions', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('correct_divisions', DbType.integer,
          defaultValue: 0, isNotNull: true),
      SqfEntityFieldBase('created_at', DbType.datetime,
          isNotNull: true, minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('updated_at', DbType.datetime,
          minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableProfile();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class DbModel extends SqfEntityModelProvider {
  DbModel() {
    databaseName = dbModel.databaseName;
    password = dbModel.password;
    dbVersion = dbModel.dbVersion;
    preSaveAction = dbModel.preSaveAction;
    logFunction = dbModel.logFunction;
    databaseTables = [
      TableProfile.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = dbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = dbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Profile
class Profile extends TableBase {
  Profile(
      {this.id,
      this.name,
      this.picture,
      this.additions,
      this.correct_additions,
      this.subtractions,
      this.correct_subtractions,
      this.multiplications,
      this.correct_multiplications,
      this.divisions,
      this.correct_divisions,
      this.created_at,
      this.updated_at}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Profile.withFields(
      this.name,
      this.picture,
      this.additions,
      this.correct_additions,
      this.subtractions,
      this.correct_subtractions,
      this.multiplications,
      this.correct_multiplications,
      this.divisions,
      this.correct_divisions,
      this.created_at,
      this.updated_at) {
    _setDefaultValues();
  }
  Profile.withId(
      this.id,
      this.name,
      this.picture,
      this.additions,
      this.correct_additions,
      this.subtractions,
      this.correct_subtractions,
      this.multiplications,
      this.correct_multiplications,
      this.divisions,
      this.correct_divisions,
      this.created_at,
      this.updated_at) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Profile.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['picture'] != null) {
      picture = o['picture'].toString();
    }
    if (o['additions'] != null) {
      additions = int.tryParse(o['additions'].toString());
    }
    if (o['correct_additions'] != null) {
      correct_additions = int.tryParse(o['correct_additions'].toString());
    }
    if (o['subtractions'] != null) {
      subtractions = int.tryParse(o['subtractions'].toString());
    }
    if (o['correct_subtractions'] != null) {
      correct_subtractions = int.tryParse(o['correct_subtractions'].toString());
    }
    if (o['multiplications'] != null) {
      multiplications = int.tryParse(o['multiplications'].toString());
    }
    if (o['correct_multiplications'] != null) {
      correct_multiplications =
          int.tryParse(o['correct_multiplications'].toString());
    }
    if (o['divisions'] != null) {
      divisions = int.tryParse(o['divisions'].toString());
    }
    if (o['correct_divisions'] != null) {
      correct_divisions = int.tryParse(o['correct_divisions'].toString());
    }
    if (o['created_at'] != null) {
      created_at = int.tryParse(o['created_at'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['created_at'].toString())!)
          : DateTime.tryParse(o['created_at'].toString());
    }
    if (o['updated_at'] != null) {
      updated_at = int.tryParse(o['updated_at'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['updated_at'].toString())!)
          : DateTime.tryParse(o['updated_at'].toString());
    }
  }
  // FIELDS (Profile)
  int? id;
  String? name;
  String? picture;
  int? additions;
  int? correct_additions;
  int? subtractions;
  int? correct_subtractions;
  int? multiplications;
  int? correct_multiplications;
  int? divisions;
  int? correct_divisions;
  DateTime? created_at;
  DateTime? updated_at;

  // end FIELDS (Profile)

  static const bool _softDeleteActivated = false;
  ProfileManager? __mnProfile;

  ProfileManager get _mnProfile {
    return __mnProfile = __mnProfile ?? ProfileManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (picture != null || !forView) {
      map['picture'] = picture;
    }
    if (additions != null || !forView) {
      map['additions'] = additions;
    }
    if (correct_additions != null || !forView) {
      map['correct_additions'] = correct_additions;
    }
    if (subtractions != null || !forView) {
      map['subtractions'] = subtractions;
    }
    if (correct_subtractions != null || !forView) {
      map['correct_subtractions'] = correct_subtractions;
    }
    if (multiplications != null || !forView) {
      map['multiplications'] = multiplications;
    }
    if (correct_multiplications != null || !forView) {
      map['correct_multiplications'] = correct_multiplications;
    }
    if (divisions != null || !forView) {
      map['divisions'] = divisions;
    }
    if (correct_divisions != null || !forView) {
      map['correct_divisions'] = correct_divisions;
    }
    if (created_at != null) {
      map['created_at'] = forJson
          ? created_at!.toString()
          : forQuery
              ? created_at!.millisecondsSinceEpoch
              : created_at;
    } else if (created_at != null || !forView) {
      map['created_at'] = null;
    }
    if (updated_at != null) {
      map['updated_at'] = forJson
          ? updated_at!.toString()
          : forQuery
              ? updated_at!.millisecondsSinceEpoch
              : updated_at;
    } else if (updated_at != null || !forView) {
      map['updated_at'] = null;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (picture != null || !forView) {
      map['picture'] = picture;
    }
    if (additions != null || !forView) {
      map['additions'] = additions;
    }
    if (correct_additions != null || !forView) {
      map['correct_additions'] = correct_additions;
    }
    if (subtractions != null || !forView) {
      map['subtractions'] = subtractions;
    }
    if (correct_subtractions != null || !forView) {
      map['correct_subtractions'] = correct_subtractions;
    }
    if (multiplications != null || !forView) {
      map['multiplications'] = multiplications;
    }
    if (correct_multiplications != null || !forView) {
      map['correct_multiplications'] = correct_multiplications;
    }
    if (divisions != null || !forView) {
      map['divisions'] = divisions;
    }
    if (correct_divisions != null || !forView) {
      map['correct_divisions'] = correct_divisions;
    }
    if (created_at != null) {
      map['created_at'] = forJson
          ? created_at!.toString()
          : forQuery
              ? created_at!.millisecondsSinceEpoch
              : created_at;
    } else if (created_at != null || !forView) {
      map['created_at'] = null;
    }
    if (updated_at != null) {
      map['updated_at'] = forJson
          ? updated_at!.toString()
          : forQuery
              ? updated_at!.millisecondsSinceEpoch
              : updated_at;
    } else if (updated_at != null || !forView) {
      map['updated_at'] = null;
    }

    return map;
  }

  /// This method returns Json String [Profile]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Profile]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      name,
      picture,
      additions,
      correct_additions,
      subtractions,
      correct_subtractions,
      multiplications,
      correct_multiplications,
      divisions,
      correct_divisions,
      created_at != null ? created_at!.millisecondsSinceEpoch : null,
      updated_at != null ? updated_at!.millisecondsSinceEpoch : null
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      id,
      name,
      picture,
      additions,
      correct_additions,
      subtractions,
      correct_subtractions,
      multiplications,
      correct_multiplications,
      divisions,
      correct_divisions,
      created_at != null ? created_at!.millisecondsSinceEpoch : null,
      updated_at != null ? updated_at!.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<Profile>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Profile.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Profile>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Profile>[];
    try {
      objList = list
          .map((profile) => Profile.fromMap(profile as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Profile.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Profile>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Profile> objList = <Profile>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Profile.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Profile by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Profile] if exist, otherwise returns null
  Future<Profile?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    Profile? obj;
    final data = await _mnProfile.getById([id]);
    if (data.length != 0) {
      obj = Profile.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Profile) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnProfile.insert(this, ignoreBatch);
    } else {
      await _mnProfile.update(this);
    }

    return id;
  }

  /// Saves the (Profile) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnProfile.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnProfile.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs Profile. Returns a new Primary Key value of Profile

  /// <returns>Returns a new Primary Key value of Profile
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<Profile> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Profile> profiles,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await DbModel().batchStart();
    for (final obj in profiles) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await DbModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < profiles.length; i++) {
        if (profiles[i].id == null) {
          profiles[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnProfile.rawInsert(
          'INSERT OR REPLACE INTO profiles (id, name, picture, additions, correct_additions, subtractions, correct_subtractions, multiplications, correct_multiplications, divisions, correct_divisions, created_at, updated_at)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',
          [
            id,
            name,
            picture,
            additions,
            correct_additions,
            subtractions,
            correct_subtractions,
            multiplications,
            correct_multiplications,
            divisions,
            correct_divisions,
            created_at != null ? created_at!.millisecondsSinceEpoch : null,
            updated_at != null ? updated_at!.millisecondsSinceEpoch : null
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Profile id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Profile id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Profile Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Profile>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Profile> profiles,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnProfile.rawInsertAll(
        'INSERT OR REPLACE INTO profiles (id, name, picture, additions, correct_additions, subtractions, correct_subtractions, multiplications, correct_multiplications, divisions, correct_divisions, created_at, updated_at)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',
        profiles,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Profile

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Profile invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnProfile
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnProfile.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Profile] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  ProfileFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return ProfileFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  ProfileFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return ProfileFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    additions = additions ?? 0;
    correct_additions = correct_additions ?? 0;
    subtractions = subtractions ?? 0;
    correct_subtractions = correct_subtractions ?? 0;
    multiplications = multiplications ?? 0;
    correct_multiplications = correct_multiplications ?? 0;
    divisions = divisions ?? 0;
    correct_divisions = correct_divisions ?? 0;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion profile

// region ProfileField
class ProfileField extends FilterBase {
  ProfileField(ProfileFilterBuilder profileFB) : super(profileFB);

  @override
  ProfileFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder isNull() {
    return super.isNull() as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as ProfileFilterBuilder;
  }

  @override
  ProfileField get not {
    return super.not as ProfileField;
  }
}
// endregion ProfileField

// region ProfileFilterBuilder
class ProfileFilterBuilder extends ConjunctionBase {
  ProfileFilterBuilder(Profile obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnProfile = obj._mnProfile;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  ProfileManager? _mnProfile;

  /// put the sql keyword 'AND'
  @override
  ProfileFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  ProfileFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  ProfileFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  ProfileFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  ProfileFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  ProfileFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  ProfileFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  ProfileFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  ProfileFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  ProfileFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  ProfileFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  ProfileField _setField(ProfileField? field, String colName, DbType dbtype) {
    return ProfileField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  ProfileField? _id;
  ProfileField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  ProfileField? _name;
  ProfileField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  ProfileField? _picture;
  ProfileField get picture {
    return _picture = _setField(_picture, 'picture', DbType.text);
  }

  ProfileField? _additions;
  ProfileField get additions {
    return _additions = _setField(_additions, 'additions', DbType.integer);
  }

  ProfileField? _correct_additions;
  ProfileField get correct_additions {
    return _correct_additions =
        _setField(_correct_additions, 'correct_additions', DbType.integer);
  }

  ProfileField? _subtractions;
  ProfileField get subtractions {
    return _subtractions =
        _setField(_subtractions, 'subtractions', DbType.integer);
  }

  ProfileField? _correct_subtractions;
  ProfileField get correct_subtractions {
    return _correct_subtractions = _setField(
        _correct_subtractions, 'correct_subtractions', DbType.integer);
  }

  ProfileField? _multiplications;
  ProfileField get multiplications {
    return _multiplications =
        _setField(_multiplications, 'multiplications', DbType.integer);
  }

  ProfileField? _correct_multiplications;
  ProfileField get correct_multiplications {
    return _correct_multiplications = _setField(
        _correct_multiplications, 'correct_multiplications', DbType.integer);
  }

  ProfileField? _divisions;
  ProfileField get divisions {
    return _divisions = _setField(_divisions, 'divisions', DbType.integer);
  }

  ProfileField? _correct_divisions;
  ProfileField get correct_divisions {
    return _correct_divisions =
        _setField(_correct_divisions, 'correct_divisions', DbType.integer);
  }

  ProfileField? _created_at;
  ProfileField get created_at {
    return _created_at = _setField(_created_at, 'created_at', DbType.datetime);
  }

  ProfileField? _updated_at;
  ProfileField get updated_at {
    return _updated_at = _setField(_updated_at, 'updated_at', DbType.datetime);
  }

  /// Deletes List<Profile> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnProfile!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnProfile!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from profiles ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnProfile!.updateBatch(qparams, values);
  }

  /// This method always returns [Profile] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Profile?
  @override
  Future<Profile?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnProfile!.toList(qparams);
    final data = await objFuture;
    Profile? obj;
    if (data.isNotEmpty) {
      obj = Profile.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Profile]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Profile?
  @override
  Future<Profile> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Profile();
  }

  /// This method returns int. [Profile]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? profileCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final profilesFuture = await _mnProfile!.toList(qparams);
    final int count = profilesFuture[0]['CNT'] as int;
    if (profileCount != null) {
      profileCount(count);
    }
    return count;
  }

  /// This method returns List<Profile> [Profile]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Profile>
  @override
  Future<List<Profile>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Profile> profilesData = await Profile.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return profilesData;
  }

  /// This method returns Json String [Profile]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Profile]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Profile]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnProfile!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Profile]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM profiles WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnProfile!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Profile]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnProfile!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Profile.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnProfile!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion ProfileFilterBuilder

// region ProfileFields
class ProfileFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fPicture;
  static TableField get picture {
    return _fPicture =
        _fPicture ?? SqlSyntax.setField(_fPicture, 'picture', DbType.text);
  }

  static TableField? _fAdditions;
  static TableField get additions {
    return _fAdditions = _fAdditions ??
        SqlSyntax.setField(_fAdditions, 'additions', DbType.integer);
  }

  static TableField? _fCorrect_additions;
  static TableField get correct_additions {
    return _fCorrect_additions = _fCorrect_additions ??
        SqlSyntax.setField(
            _fCorrect_additions, 'correct_additions', DbType.integer);
  }

  static TableField? _fSubtractions;
  static TableField get subtractions {
    return _fSubtractions = _fSubtractions ??
        SqlSyntax.setField(_fSubtractions, 'subtractions', DbType.integer);
  }

  static TableField? _fCorrect_subtractions;
  static TableField get correct_subtractions {
    return _fCorrect_subtractions = _fCorrect_subtractions ??
        SqlSyntax.setField(
            _fCorrect_subtractions, 'correct_subtractions', DbType.integer);
  }

  static TableField? _fMultiplications;
  static TableField get multiplications {
    return _fMultiplications = _fMultiplications ??
        SqlSyntax.setField(
            _fMultiplications, 'multiplications', DbType.integer);
  }

  static TableField? _fCorrect_multiplications;
  static TableField get correct_multiplications {
    return _fCorrect_multiplications = _fCorrect_multiplications ??
        SqlSyntax.setField(_fCorrect_multiplications, 'correct_multiplications',
            DbType.integer);
  }

  static TableField? _fDivisions;
  static TableField get divisions {
    return _fDivisions = _fDivisions ??
        SqlSyntax.setField(_fDivisions, 'divisions', DbType.integer);
  }

  static TableField? _fCorrect_divisions;
  static TableField get correct_divisions {
    return _fCorrect_divisions = _fCorrect_divisions ??
        SqlSyntax.setField(
            _fCorrect_divisions, 'correct_divisions', DbType.integer);
  }

  static TableField? _fCreated_at;
  static TableField get created_at {
    return _fCreated_at = _fCreated_at ??
        SqlSyntax.setField(_fCreated_at, 'created_at', DbType.datetime);
  }

  static TableField? _fUpdated_at;
  static TableField get updated_at {
    return _fUpdated_at = _fUpdated_at ??
        SqlSyntax.setField(_fUpdated_at, 'updated_at', DbType.datetime);
  }
}
// endregion ProfileFields

//region ProfileManager
class ProfileManager extends SqfEntityProvider {
  ProfileManager()
      : super(DbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'profiles';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion ProfileManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await DbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await DbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await DbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class DbModelSequenceManager extends SqfEntityProvider {
  DbModelSequenceManager() : super(DbModel());
}
// END OF ENTITIES
